workflows:
  ios-workflow:
    name: iOS Build

    environment:
      xcode: latest

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.shunokamoto.Countdown

    scripts:
      - name: Set up code signing
        script: |
          xcode-project use-profiles

      - name: Build ipa
        script: |
          xcode-project build-ipa \
            --project "カウントダウン.xcodeproj" \
            --scheme "カウントダウン"

    artifacts:
      - build/ios/ipa/*.ipa
